# HTTP Server
[server]
	AddressServer     = "82"
	AddressClient     = "81"
	ServerRoot  = "public"
	ServerAgent = "Aliyun_nginxServer" # Aliyun_nginxServer Aliyun_nginxClient
	LogPath     = "logs/"
# Logger.
[logger]
    Path        = "./logs/Aliyun_nginxServer" # Aliyun_nginxServer Aliyun_nginxClient
    Level       = "all"
    Stdout      = true

# 自定义参数
[myconfig]
    #公共参数
    sign_key="1111111111111"

    #云服务器配置
    max_retry       = 10 #当公网ip边后，客户端重试次数. 之后发邮件告警
    email_host=""
    email_name=""
    email_keypassword=""
    #nginx_conf_paths=["/usr/local/nginx/mywebsiteconf/homeapp.top.conf","/usr/local/nginx/mywebsiteconf/47.115.20.59.conf"] #需要修改的文件数组

     nginx_conf_paths=["C:/Users/Administrator/Desktop/nginx/homeapp.top.conf","C:/Users/Administrator/Desktop/nginx/47.115.20.59.conf"] #需要修改的文件数组

    #动态电脑配置
    my_yunserver_ip       = "localhost" #阿里云 or 腾讯云 ip  47.115.20.59


[compiler]
    name     = "Aliyun_nginxServer"
    version  = "1.0.0"
    arch     = "i386,amd64"
    system   = "linux,windows"
    output   = ""
    path     = "./bin"
    CGO_ENABLED = "1"
    extra    = "-ldflags \"-s -w\""
    # 自定义编译时内置变量
    [compiler.VarMap]
        author = "adminD"
        email  = "2642000280@qq.com"
